before_install:
    - fusermount -V

install:
    - sudo apt-get install libfuse-dev

before_script:
    - mkdir mount
    - |
      sudo chmod a+rw /dev/loop0
      dd if=/dev/zero bs=512 count=2048 of=disk
      losetup /dev/loop0 disk

script:
    - make
    - ./lfs --format /dev/loop0
    - ./lfs /dev/loop0 mount
    - cd mount && ls
    - cp -r ../littlefs .
    - cd littlefs && ls
    - make -B test_dirs
    - make -B test_files
